sudo: false
language: python
python: 3.6
env:
  matrix:
    - ENV=test
    - ENV=check
    - ENV=test_nvim
install:
  - |
    if [ "$ENV" = "test" ]; then
      python3.6 -m pip install pytest
    fi
  - |
    # https://github.com/neovim/bot-ci#generated-builds
    if [ "$ENV" = "test_nvim" ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
      pip --version
      pip install neovim
    else
      vim --version
    fi
script:
  - make --keep-going "$ENV"
